name: Deploy Gitbook to GitHub Pages

# Указываем триггер для запуска workflow при пуше в ветку main
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Шаг для клонирования репозитория

    - name: Set up Node.js
      uses: actions/setup-node@v2 # Шаг для установки Node.js
      with:
        node-version: '12' # Указываем версию Node.js

    - name: Install GitBook CLI
      run: npm install -g gitbook-cli # Устанавливаем GitBook CLI глобально
      run: npm install graceful-fs@latest --save

    - name: Install GitBook plugins
      run: gitbook install docs # Устанавливаем необходимые плагины GitBook

    - name: Build GitBook
      run: gitbook build docs # Собираем проект с помощью GitBook

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # Используем действие для деплоя на GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Используем токен GitHub для авторизации
        publish_dir: ./docs/_book # Указываем директорию для публикации